/**
 * A Pattern generated by a user from a selection of templates
 */

export interface IDesign {
  patterns?: IPattern[] | IBlankRow[];
  name?: string;
  createdDate?: Date;
  modifiedDate?: Date;
}

/**
 * A Template that a user can design then select to build a pattern 
 */

export interface IBlankRow {

}

export interface IPatternCell {
  isForeground?: boolean;
  color?: string;
}

export interface IPatternRow {
  cells: IPatternCell[];
}

export interface IPattern {
  rows: IPatternRow[];
  name: string;
  id: string;
}