/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPatternFromDiscriminatorValue, type Pattern } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Patterns
 */
export interface PatternsRequestBuilder extends BaseRequestBuilder<PatternsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Pattern[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Pattern[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PatternsRequestBuilderUriTemplate = "{+baseurl}/Patterns";
/**
 * Metadata for all the requests in the request builder.
 */
export const PatternsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PatternsRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createPatternFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
